name: wie_moet_er_bier_gaan_halen
description: "A flutter application to make your drinking rounds more fair"
publish_to: 'none'
version: 1.1.1+2

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  confetti: ^0.7.0
  shared_preferences: ^2.2.3
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  firebase_database: ^12.1.1
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.1.4

  cupertino_icons: ^1.0.8

  intl: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#F57C00"

flutter:

  uses-material-design: true
  generate: true
